### ISSUE TITLE
Peppermint fail and Console fails

### ISSUE THREAD

**Issue by enesozturk** [jacobtomlinson/carte-noire#68]
I've forked the project, changed the name. When I open the blog I encounter with some errors and I can't see peppermint(colorful code blocks).
When I run the project in local and open localhost:4000, there is no problem, I can see colorful code blocks.
What I'm missing?
![1](https://cloud.githubusercontent.com/assets/19428358/18036685/92118246-6d7a-11e6-81f7-da6119a0d419.JPG)

**Comment by CarMoreno** [comment]
@oztrkeness  Do you have installed Rouge gem in your pc?

**Comment by mrdaveanderson** [comment]
@CarMoreno So does this not work on pages.github.io then? I've just discovered I'm having the same issue (hosted on pages.github.io).

**Comment by mrdaveanderson** [comment]
For me it seems perhaps that the auto upgrade to https is breaking some .js loading in the theme when served from github.io.

**Comment by mrdaveanderson** [comment]
It appears that when serving from pages.github.io using https, highlight is not getting loaded due to https pages trying to load the highlighting javascript library over http, which is blocked due to not being secure.

**Comment by mrdaveanderson** [comment]
I was able to fix this by replacing http with https in the files located in _includes (and maybe a couple of the other directories...but it was pretty easy...seems to work so far)

Also stripped out the google font stuff at the top of styles.scss

**Comment by enesozturk** [comment]
@CarMoreno Yes I've installed. Thank you.
@mrdaveanderson Thank you. Your advices helped me! But I don't understand why I recieved 'https' and 'google font'  errors?

**Comment by mrdaveanderson** [comment]
Because github served the main page over https, but then that page says it wants to load javascript over http (which is not secure), which most browsers do not allow any more. This is because insecure javascript can negatively impact the security of the main site, which since it was served over https, the browser assumes you wanted to view it securely.

Changing all of those resources to load over https fixes the problem.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. And thanks to everyone for debugging it. It would be really helpful if one of you could raise a PR with these fixes in.

**Comment by mrdaveanderson** [comment]
Hm. I forked from @jacobtomlinson 's master version in a clean repo (again) and set it up to serve from my account, to make sure I only grabbed relevant changes and could re-test, and now it wont repro. Possible that github has started rewriting http links as https? Should I still change what I can recall and attempt a pr?

**Comment by mrdaveanderson** [comment]
Oh, I see what it is. If you change the url in the _config.yml url: "https://<user>.github.io/carte-noire/" where it starts with https, then things break as we described in this thread (which is odd, because I'm positive mine said http when this whole thing started over the weekend, so perhaps github did change something this weekend for awhile...or something).

**Comment by mrdaveanderson** [comment]
@jacobtomlinson you should have a PR for this now...probably. Pretty new to github. Seems like it worked though. Eventually.
